### ISSUE TITLE
julian2UTC.m

### ISSUE THREAD

**Issue by spto** [kalyan0510/Sun-and-Satellite-transit-predict#1]
t.TimeZone = '-05:30';

should be removed from julian2UTC.m, or it will return wrong results.

Thank you for writing the very useful code.

Cheers
Boyang

**Comment by kalyan0510** [comment]
Hi Boyang.
I am from IST so I added that line. but ideally I should have pulled that from system clock. 
Thanks for pointing. :)

**Comment by kalyan0510** [comment]
Fixed it in the rep
